### ISSUE TITLE
Angular 2 Example

### ISSUE THREAD

**Issue by jcbowyer** [adrianhall/develop-mobile-apps-with-csharp-and-azure#33]
Thanks so much for this great work.  This is not really an issue but rather a request.   It would be great if you could provide an angular 2 example in addition to the current angular example.   This would be of great help to people looking to get started in angular 2 for azure and I have not been able to find any similar quickstarts on the web.

**Comment by adrianhall** [comment]
Totally agreed.  I think I mentioned this - I'm not an Angular 2 expert, but I'll see what I can cobble together and add to chapter 6.

**Comment by jcbowyer** [comment]
Thanks so much.  If you want me to preview or test anything, let me know.

**Comment by aline-almeida** [comment]
I've got this working with angular 4, except for one thing: I can't seem to use the client flow authentication.
Using adal.js 1.0.15, I successfully login and get the token. Then when I try to login in the backend with that token: ` msclient.login('aad', { 'access_token': token }) `, I get a 401 error: "You do not have permission to view this directory or page." If I use `msclient.login('aad') ` , then a popup window opens & closes right away and the login operation succeeds without having to enter anything. (I believe the token is being sent along with the request). I would like to login silently in the backend, since I already have the token. What am I missing ?

**Comment by adrianhall** [comment]
Unfortunately, I am no longer a member of the technical staff at Microsoft, so I cannot assist with this.  I'd recommend reaching out on Stack Overflow to the AAD team on this one.

**Comment by aline-almeida** [comment]
Too bad! You were doing a great job.
Thanks, I'll try that.

**Comment by aline-almeida** [comment]
Just in case someone bumps into the same problem I did, please check the answer here: [https://stackoverflow.com/questions/46664208/angular-4-add-authentication-against-azure-mobile-app-with-adal-js-token](https://stackoverflow.com/questions/46664208/angular-4-add-authentication-against-azure-mobile-app-with-adal-js-token)

**Comment by adrianhall** [comment]
Closing this one as the original issue will not be completed.
