### ISSUE TITLE
[Question] How to have a login form in a merged MVC app using custom auth?

### ISSUE THREAD

**Issue by julianonunes** [adrianhall/develop-mobile-apps-with-csharp-and-azure#36]
I'm kind of desperate to achieve the results I need because my project's deadline is arriving and I have not been able to finish the auth for the merged MVC app and mobile client.

I've created the login form and auth code using ASP.Net Identity just like I usually do for ASP.Net MVC projects not deployed to App Service. However on chapter 6 you mention the need to add the <authentication> element to the web.config:

```
<authentication mode="Forms">
      <forms loginUrl="/.auth/login/custom" timeout="2880"/>
    </authentication>
```

I've created the custom AuthController querying the ASP.Net Identity tables, but I don't know how can I redirect to the Login form without breaking the authentication for mobile client. What do you suggest? Can you help me?

```
[Route(".auth/login/custom")]
    public class AuthController : ApiController
    {
        private ApplicationDbContext db;

        public AuthController()
        {
            db = new ApplicationDbContext();
        }

        public HttpResponseMessage Post(LoginChallenge challenge)
        {
            // return error if password is not correct
            if (!this.IsPasswordValid(challenge.Username, challenge.Password))
            {
                return this.Request.CreateUnauthorizedResponse();
            }

            JwtSecurityToken token = this.GetAuthenticationTokenForUser(challenge.Username);

            return this.Request.CreateResponse(HttpStatusCode.OK, new
            {
                Token = token.RawData,
                Username = challenge.Username
            });
        }

        private JwtSecurityToken GetAuthenticationTokenForUser(string username)
        {
            var claims = new Claim[]
            {
                new Claim(JwtRegisteredClaimNames.Sub, username)
            };

            var signingKey = this.GetSigningKey();
            var audience = this.GetSiteUrl(); // audience must match the url of the site
            var issuer = this.GetSiteUrl(); // audience must match the url of the site 

            JwtSecurityToken token = AppServiceLoginHandler.CreateToken(
                claims,
                signingKey,
                audience,
                issuer,
                TimeSpan.FromHours(24)
                );

            return token;
        }

        private bool IsPasswordValid(string username, string password)
        {
            // this is where we would do checks agains a database
            return db.Users.Count(u => u.UserName.Equals(username) && u.PasswordHash.Equals(password)) > 0;
        }

        private string GetSiteUrl()
        {
            var settings = this.Configuration.GetMobileAppSettingsProvider().GetMobileAppSettings();

            if (string.IsNullOrEmpty(settings.HostName))
            {
                return "http://localhost:60895/";
            }
            else
            {
                return "https://" + settings.HostName + "/";
            }
        }

        private string GetSigningKey()
        {
            var settings = this.Configuration.GetMobileAppSettingsProvider().GetMobileAppSettings();

            if (string.IsNullOrEmpty(settings.HostName))
            {
                // this key is for debugging and testing purposes only
                // this key should match the one supplied in Startup.MobileApp.cs
                return ConfigurationManager.AppSettings["SigningKey"];
            }
            else
            {
                return Environment.GetEnvironmentVariable("WEBSITE_AUTH_SIGNING_KEY");
            }
        }
    }
```

**Comment by adrianhall** [comment]
Basically, you can't.  You are going to have two authentication methods - your login form for your MVC app and a custom auth technique for your mobile app.  Both will work independently from one another, although they reference the same authentication data source.

**Comment by nhwilly** [comment]
Sorry to be so dense, but does this mean that we don't use the `<authentication>` tag in the web.config and instead do something else?  I would guess that `401` responses get handled in JS in the browser?

**Comment by adrianhall** [comment]
I've not actually done it.  The idea would be that the web.config would point to your MVC page for handling logins.  The Mobile would have to explicitly login through the normal mechanism.  Both *SHOULD* be handled appropriately.  However, I've never done it.

**Comment by nhwilly** [comment]
OK, thanks.  I'll just add a couple of revelations/unfounded opinions I've developed doing this.  Maybe it'll help you with the book or some other victim.  Or me by talking aloud to no one.

Background: Relying on external identity providers is the *only* way to go with the state of the internet and the current surplus of lawyers.  However, I have a financial app and that means I cannot rely on social providers exclusively.  People simply change them around too often and getting locked out of your money won't be popular.  AAD is too expensive for a free consumer facing app and that leaves us with B2C as the only real workable solution.  If I can't get that to work, I might as well drop the project and go sit on a beach.  

By the way, none of this matters a whit if you aren't trying to run your browser based web app out of the same site as your mobile API site.  It's that `<authentication>` tag that is the show stopper.  If you're not doing that you can quit reading right now.  Or, if by the time you read this, MSAL combined with B2C is actually working with ZUMO, then you can just do the native SDK approach, leave the `<authentication>` in place and go back to work.

Also, because it's a financial app, I really don't want SSO.  Just because they are running Facebook, they should automatically be signed into my app.  And I don't want someone else (not B2C and especially not Facebook) controlling my refresh tokens.  Which makes the  plurality of native SDK solutions less attractive.

The problem really surfaces in attempting to issue additional claims in my own token while first relying on an external provider (like B2C).  Technically, they authenticate with B2C, then, in another call, reach a protected custom endpoint which develops the additional claims.  If that fails, then I was returning a 401.

In thinking about it, it might just be that "Forbidden" is a better response under these circumstances.  The initial authentication might actually be just fine.  So, technically, they *are* authenticated.  They just don't have what it takes to be permitted to access the resources they want.  And forbidden's are not redirected.

My tokens expire every hour and I refresh them silently.  That's fine.

Where my stuff hit the wall was when my custom refresh token finally expired (say, after 6 months) and they have to re-authenticate.  Ditto for system wide password reset.  That's not a forbidden operation, they actually have to login with the original provider again.  

And that's where the MVC redirect sends them off with a 302 and the mobile clients promptly barf.

In the meantime, I'm punting, going to UserVoice, whining and voting my little votes and pulling the MVC `<authentication>` tag out of the web.config.  I'll just have to figure it out later.

**Comment by adrianhall** [comment]
Have you thought about integrating Auth0 in your solution?  I think it meets all your requirements.

**Comment by nhwilly** [comment]
I looked at the pricing and it seemed pretty high.  This app is driven by merchants, who will force usage on their customers.  I know that sounds like it's total fantasy, but it's not really.  They already have that kind of relationship and do it for many other things.  Merchants pay, consumes are free.

If we don't get to 100,000 active consumer downloads, then this won't fly.  At those numbers, the authentication count could get expensive.  That's one of the reasons for my focus on refresh tokens controlled by me.  Auth0 doesn't list a price for 100,000 active users, so I'll contact them.

At 50,000 active users, Auth0 is $850 a month and B2C is zero.  With B2C, the additional authentications cost money, but assuming that every mobile client will use the app 3 times a week and logout each time (a worst case scenario) the B2C solution is $1,800 a month for 100,000 users.  But I firmly believe that most mobile app users are hopelessly irresponsible and will just never logout, choosing to let the tokens silently refresh against my endpoint in the background.

If by some stroke of luck this scales to any real degree, the Auth0 becomes quite expensive and while the B2C might get expensive, my bet is that it won't due to the refresh tokens.

I sure don't want to start with one authentication scheme and switch.  That sounds *really* painful.

Honestly, I'm not young (my first commercial app debuted in 1978) and it wasn't until I actually saw tools like Xamarin, B2C and ZUMO that I thought I could actually get back to development.   I truly thought that MSAL would have it together by now.  MSAL seems to have been in the "experimental" stage for a quite long time. It makes me nervous to count on them to get it working before I get to market.  And that doesn't count the fact that social network providers (which I would offer as convenient secondary logins) don't seem to work consistently and the activity on the projects on GitHub seems pretty old.

Honestly, if MSAL worked with B2C for ZUMO, I'd have been done with identity a month ago.

I retired early, my kids are gone and I'm working on this literally seven days a week.   Everything has been pretty great - Except the Identity Tar Pit.

Your book has saved my bacon.  Actually it seems like every question I have has been anticipated.  

I'll just punt on the MVC tie in for now.  Who knows, maybe I can make the app stand alone without a website at all.  Unlikely, but popular apps have done it before.
