### ISSUE TITLE
How-to: Backend Validation on removed record

### ISSUE THREAD

**Issue by ericbrunner** [adrianhall/develop-mobile-apps-with-csharp-and-azure#43]
Hi Adrian,

I have a case where the record that was previously assigned to a specific user gets removed from that user in backoffice inside Sql DB and assigned to another user. I need to add some code in the PATCH methods of my controllers like you described in Chapter 3:

public Task<TodoItem> PatchTodoItem(string id, Delta<TodoItem> patch)
{
    ValidateOwner(id);
    return UpdateAsync(id, patch);
}

Do I have to do a special error handling in my App Frontend code or is it handled in proper setup conflict handling code, so that that localItem update gets locally in the App DB discharded?

Is the error.Result in that case null I guess.

Thanks

Eric

**Comment by adrianhall** [comment]
I saw the Stack Overflow on this.  I don't know why you are getting error.Result == null.   You are going to have to trace it through (since I don;t have a repro).  

You always need to handle cases where 500 or 404 responses happen (both will result in an error.Result == null, but will also have exceptions associated with them that aren't conflicts)

**Comment by ericbrunner** [comment]
> You always need to handle cases where 500 or 404 responses happen (both will result in an error.Result == null, but will also have exceptions associated with them that aren't conflicts)

Ok when I handle that eceptions, is my Pending Operation then gone? Or how could I cancel that specific pending Op?

**Comment by adrianhall** [comment]
The pending operation is still there.  You need to fix the 500 first - that's a server crash.  You can also purge the queue.
