### ISSUE TITLE
Add Account/User-Management

### ISSUE THREAD

**Issue by filoe** [adrianhall/develop-mobile-apps-with-csharp-and-azure#68]
The book describes how implement an authentication process using different login providers.
I need to store some information of the user in the backend database. That means I would need some kind of registration process. I can't find any details in the book on a registration process for social providers.

You may add a note on where I would have to check whether the user exists in the database or not. That spot should also grant me access to all the user related data of the social provider (email, userid, ...).

It is related to this thread: https://stackoverflow.com/questions/44218556/register-a-user-within-asp-net-identify/44237816

**Comment by adrianhall** [comment]
All the information is in there.  I don't cover every scenario because there are an infinite number of those and I'd never be finished.  I cover how to read the auth data from a social provider, how to connect to a database, and how to invoke a custom API.  I don't think there is a need for additional work.
