### ISSUE TITLE
Personal Doubt!!!

### ISSUE THREAD

**Issue by Quico20** [adrianhall/develop-mobile-apps-with-csharp-and-azure#84]
Hey Adrian, firstable you scared me, I've been using your book as a great Azure Mobile Apps reference, big source, but man, you were at github, then moved to gitlab and yesterday i was trying to read about push notifications because its been a long time since I read that chapter and put it on practice, and found a 404 error ate gitlab.

Could you be so kind and tell me why did you moved back to github???(i'm just curious).

by the way great source, also found your 30 day bootcamp on azure and its also has techiniques you didnt considered in this book, great sources, its a pity that you arent working on Azure anymore.

**Comment by scout208** [comment]
I had the same scare as you @Quico20. I also rely on this resource a lot and am sad, Adrian, that you aren't working on Azure anymore. Your's are the best resources for working on Azure Mobile Apps in my opinion as the docs and other blogs don't go into nearly as much detail as you do and leave a lot of things up to guess.

**Comment by adrianhall** [comment]
Well, good news is that I'm back at Microsoft, as of last week.  I've just picked up the book again and realized it needed a complete rewrite because of what has happened in the development world int he last three years since I wrote the book, so I'm working on a refresh.

As to why gitlab vs github - it's an unfortunate side effect of my split of work between Microsoft and Amazon.  I got a lot of opinions about dropping GitHub (universally negative), so I moved the stuff I could back.
